### ISSUE TITLE
Show bird metadata

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/bird-tracking#42]
Use [bird_tracking_devices](https://lifewatch-inbo.cartodb.com/tables/bird_tracking_devices) to populate the `bird-metadata` https://github.com/LifeWatchINBO/bird-tracking/issues/39#issuecomment-55260181 with info on the selected bird.

## Tasks

* [x] Load species
* [x] Load sex
* [x] Reload when selecting another bird
* [x] Think about best way to display this (pipe separated, labels?)
* [x] Think what other info we could add

## Example

    Species: Larus fuscus | Sex: female

**Comment by bartaelterman** [comment]
Other info to add:

- catch location
- catch date
- ring code

The pipe symbol is fine, but the labels aren't necessary (`Larus fuscus | female` is as clear as `Species: Larus fuscus | Sex: female`)

**Comment by peterdesmet** [comment]
I agree with everything to add, and would use labels (especially with the new info).

**Comment by bartaelterman** [comment]
I added that information. However, the metadata now requires 2 rows, and is not very clear anymore. I would suggest:

- drop the catch date. That is pretty obvious from the chart.
- drop the catch location. For most birds, it's pretty clear where they were caught, because most of there tracks are from that area. We can consider to add a dot to the map indicating the catch location. It makes more sense to add this information to the map.
- Reformat the line as: `Larus fuscus, female, ringed "YLAT"`

**Comment by peterdesmet** [comment]
1. Agree
2. Dot on the map would be great. I still think a text indication is nice as well.
3. Will do

**Comment by peterdesmet** [comment]
17bc044d5d8a798b4e472c75aaae8b9db9a00a07: now shows as `Male Larus argentatus (H903185), catched in 2013.`

**Comment by bartaelterman** [comment]
That should be `caught`.

**Comment by bartaelterman** [comment]
Looks neat!

**Comment by peterdesmet** [comment]
Fixed: 2db7561756a6b4f1bb6a8864901faae8d2d568f3
