### ISSUE TITLE
Add year chart navigation

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/bird-tracking#44]
Add arrows left (`previous-month`) and right (`next-month`) of the `year-chart` so that the calendar can be navigated forwards and backwards in time (one month at a time).

## Tasks

* [x] Add arrows (@peterdesmet)
* [x] Clicking navigation should trigger a call
* [x] New month should be loaded
* [x] Calendar should slide to new position
* [ ] Clear any selection
* [ ] Effected elements should load new data, see interaction E in https://github.com/LifeWatchINBO/bird-tracking/issues/39#issuecomment-55262417

**Comment by bartaelterman** [comment]
I'm assigning you to this issue first. There's not much I can do without the arrows.

**Comment by peterdesmet** [comment]
Arrows added in 6ab37d543e5a0d06c61517a74d9c9cb9267b4dc0, assigned to you. Use the ids (`previous-month` and `next-month`) to trigger.

**Comment by bartaelterman** [comment]
As discussed in #39 navigating the year calendar will not clear the selection.
