### ISSUE TITLE
Add day selection to year chart

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/bird-tracking#45]
Add functionality to `year-chart` so that user can select a day.

## Tasks

* [x] Trigger a call when selecting a day
* [x] Effected elements should load new data, see interaction C in #39 (comment)
* [x] Highlight the selected day (black border)
* [x] Add button to clear selection (@peterdesmet)
