### ISSUE TITLE
Add month selection to year chart

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/bird-tracking#46]
Add functionality to `year-chart` so that user can select a month.

## Tasks

* [x] Trigger a call when selecting a month label
* [x] Effected elements should load new data, see interaction D in #39 (comment)
* [x] Highlight the selected label (bold?)
* [x] Add button to clear selection (@peterdesmet)
* [x] Make it clear to user that months can be selected.
