### ISSUE TITLE
Add metric selection

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/bird-tracking#48]
Selecting a metric in `select-metric` loads data for that metric.

## Tasks

* [x] Effected elements should load new data, see interaction B in https://github.com/LifeWatchINBO/bird-tracking/issues/39#issuecomment-55262417
* [x] Use `active` class to indicate current metric
* [x] No problem in adding an ID for each metric
