### ISSUE TITLE
Show selected time frame

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/bird-tracking#49]
Show the timeframe selected in `year-chart` in `selected-time`. The time should be displayed in a nice readable way, e.g. `Tuesday April 1, 2013`.

## Tasks

* [x] Year selection: `April 2013 to March 2013`
* [x] Month selection: `April 2013`
* [x] Day selection: `Tuesday, April 1 2013`
* [x] Reload on new selection or when returning to default
* [x] See https://github.com/LifeWatchINBO/bird-tracking/issues/39#issuecomment-55262417 to see what interactions trigger a reload

**Comment by bartaelterman** [comment]
In #39 I only see a month selection (by clicking on the label) and a day selection (by clicking on one cell). I don't see a way to do a year selection.
