### ISSUE TITLE
Show metric metadata

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/bird-tracking#50]
Add metadata on the metric selected in `select-metric` in `metric-metadata` .

## Tasks

* [ ] Decide what metric metadata to show for each metric, e.g. maximum distance from catch location, speed
* [ ] Reload on new selection or when returning to default
* [ ] See https://github.com/LifeWatchINBO/bird-tracking/issues/39#issuecomment-55262417 to see what interactions trigger a reload

**Comment by bartaelterman** [comment]
Maybe averages are more interesting. The maxima should be pretty clear from the month calendar chart:

- average distance travelled per day for this selection
- average maximum distance from catch location per day. (should think of a better way to formulate this. I mean: 'on average, how far does this bird travel from his nest on one day')
