### ISSUE TITLE
Add map

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/bird-tracking#51]
Add a CartoDB map, showing occurrences of the selected bird and timeframe.

## Tasks

* [ ] Create a CartoDB viz (@peterdesmet)
* [x] Include the viz (basemap, legend, buttons, etc.)
* [x] Load the data for the selected bird and timeframe (I'm not sure how this interacts with the viz?)
* [x] Reload on new selection or when returning to default
* [x] See https://github.com/LifeWatchINBO/bird-tracking/issues/39#issuecomment-55262417 to see what interactions trigger a reload

**Comment by bartaelterman** [comment]
@peterdesmet is this viz already created? I'm not sure this will work with a viz because the explorer needs to be able to query a subset of the data (one month, or one day) and then create a map with only that data. We might need to construct the viz from the explorer using the Cartodbjs library (the way it was implemented in release 1).

**Comment by bartaelterman** [comment]
Checked the documentation. We'll need to [create the viz at runtime](http://docs.cartodb.com/cartodb-platform/cartodb-js.html#creating-visualizations-at-runtime). There is no way to subset the data of a predefined viz so no need to create one.

**Comment by bartaelterman** [comment]
We do need to discuss the baselayer and the style for the data.

**Comment by bartaelterman** [comment]
Created #57 for the map styling. This issue will close when 6a53805 is merged into master.

**Comment by bartaelterman** [comment]
See #65

If it's not possible to update the sql of a viz, we should switch back to generating a viz at runtime.

**Comment by bartaelterman** [comment]
#65 fixed. That fixes this issue as well.
