### ISSUE TITLE
Add month chart

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/bird-tracking#52]
Add a calendar heat map in `month-chart`, showing the data for the selected bird and timeframe.

## Tasks

* [x] 24 hours (horizontal)
* [x] 29-31 day (vertical)
* [x] Labels for hours
* [x] Labels for days
* [x] Load metric in each block
* [x] Add legend
* [x] Show a tooltip?
* [x] When day is selected, highlight the day row
* [x] When year is selected (= default view), empty chart
* [ ] When year is selected, show some explanatory text in the div
* [x] Reload/empty on new selection or when returning to default
* [x] See https://github.com/LifeWatchINBO/bird-tracking/issues/39#issuecomment-55262417 to see what interactions trigger a reload

**Comment by bartaelterman** [comment]
Added an optimisation: month map is only redrawn if the user clicks on a different month.

**Comment by bartaelterman** [comment]
Most of it is fixed. Just need to make sure it refreshes when the metric is toggled.
