### ISSUE TITLE
Add day chart

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/bird-tracking#53]
Add a line chart to `day-chart`, showing the data for the selected bird and day.

## Tasks

* [x] 24 hours (horizontal: x)
* [x] Metric (vertical: y)
* [x] Labels for hours
* [x] Axis for metric
* [x] Add legend
* [x] Show a tooltip?
* [x] When year is selected (= default view), empty chart
* [x] When month is selected, empty chart
* [x] When year or month is selected, show some explanatory text in the div
* [x] Reload/empty on new selection or when returning to default
* [x] See https://github.com/LifeWatchINBO/bird-tracking/issues/39#issuecomment-55262417 to see what interactions trigger a reload
* [x] Reload nicely (e.g. move in place)

**Comment by bartaelterman** [comment]
Currently, the chart shows the timestamps on the x-axis that are present in the data. In order to be able to set the x-axis to always show 24 hours, I would need to know how to pass missing data to C3. Do you know how to do this?

**Comment by bartaelterman** [comment]
The default C3 tooltip is shown. If we leave this on, I think it should have the same style as the heatmap tooltips.

**Comment by peterdesmet** [comment]
To answer your question, I'd have to see the current chart: I don't see it in the live application, is it already there?

**Comment by bartaelterman** [comment]
pushed!

**Comment by bartaelterman** [comment]
To explain it with code:

The data format is something like:
```
{
    columns: [
        ["x", 1, 2, 3, 4],
        ["distance", 20, 10, 4, 23]
    ]
}
```

Currently, if one or more timestamps would be missing, the arrays would just have less then 25 values. If we would try to fix the x-axis, I think you need to make sure you always provide a column array with "x" as first element and next elements ranging from 0 to 23. But say you don't have data for 0h, then what do you put on that position in the "distances" array? `null`?

**Comment by peterdesmet** [comment]
Yep, `null` works. Or, you can set axis type to `timeseries`: http://c3js.org/samples/timeseries.html

**Comment by bartaelterman** [comment]
Ok, I'll make sure the first array in the `columns` property always contains 25 elements ('x', and 0 to 23) and the next column contains `null` if there is no data for a given hour.

**Comment by bartaelterman** [comment]
fixed here: bbef7b746c85f8551c9af5c31145151ede627821

The chart does not connect dots if there is no data in between. (see for example bird Jurgen, on February 3, 2014). Exactly what we wanted.

**Comment by bartaelterman** [comment]
`When year or month is selected, show some explanatory text in the div` This could be done with the `empty` tag from C3 but then the chart must be initialised immediately (and never be removed completely) and the user will always see the axes.

The other option is to just insert text in the div by default, and show/hide that as appropriate.

**Comment by bartaelterman** [comment]
Implemented the text in 25cf33a6332a4f4de1a3ba6997cfea3c722f38c2.
Text can be changed if preferred.
